### PR TITLE
dockerized

### PR DESCRIPTION
**Pull request by Difrex**
Dockerized environment. 

Build app:
docker build -t potracheno .

Run app:
docker run -d -p 5000:5000 --name potracheno potracheno

### CODE REVIEW

**Comment by dallaylaen** [comment]
Tried to build on my laptop, got this: 

<pre>bash$ sudo docker build -t potracheno .
[sudo] password for lodin: 
Sending build context to Docker daemon 10.23 MB
Sending build context to Docker daemon 
Step 0 : FROM perl:5.24.0
5.24.0: Pulling from perl
32734c6d04f6: Pull complete 
1849b6667515: Pull complete 
4dc0c76ee6ce: Pull complete 
b74c739ef73e: Pull complete 
b8a55ac0c99e: Pull complete 
0334733362b7: Pull complete 
3f9a4c5153c3: Pull complete 
a13e1403afdb: Pull complete 
6b806def2e17: Pull complete 
fa70df54e2d7: Pull complete 
ddffc84fab3f: Pull complete 
bd2927153d02: Pull complete 
fee83321f0ed: Pull complete 
Digest: sha256:62f217f4324b2c5153cbcb3ff9ba24c8040579eabff5b8310b4ca2aaefe82a9c
Status: Downloaded newer image for perl:5.24.0
 ---> fee83321f0ed
Step 1 : MAINTAINER Denis Zheleztsov <difrex.punk@gmail.com>
 ---> Running in 298125ae7461
 ---> f1554239a30b
Removing intermediate container 298125ae7461
Step 2 : COPY . /app
 ---> fa5057001f99
Removing intermediate container 3b9fba88f93c
Step 3 : RUN cpanm DBD::SQLite Text::Markdown MVC::Neaf JSON::XS LWP::UserAgent
 ---> Running in e1e21e38e14b
exec format error
INFO[0072] [8] System error: exec format error  </pre>

What am I doing wrong? Docker is a good idea, would love to add.

**Comment by Difrex** [comment]
Hmmm, are you use 32b system? Most docker images is 64b.

**Comment by dallaylaen** [comment]
Yes, x86. Could you please add a comment that 64 bit is required?

**Comment by Difrex** [comment]
I'm added some comments for building your own 32bit base image

**Pull request merged**
